### ISSUE TITLE
关于协同过滤中计算最终得分的问题

### ISSUE THREAD

**Issue by KyrieXDL** [datawhalechina/team-learning-rs#2]
例如基于物品的协同过滤中，通过相似的k个物品计算用户对这个物品的分数，但是如果用户对于对于相似物品的评分也是nan的时候，是作为0处理吗？还有在完整实现代码这种，为什么计算分数就仅仅只是相似度的一个求和，而没有使用说的加权以及减去平均的这种做法呢？

**Comment by RuyiLuo** [comment]
1. 一个用户历史喜欢商品相似的商品，在使用的时候往往这些商品并不是该用户历史交互的商品，所以用户对于相似商品本身就没有直接的评分值，此外这些商品是其他用户喜欢的商品，而在倒排表字典中的值本身就是有效的。
2. 分数直接求和是一种比较简单的计算方式，在教程文档中介绍了一种稍微复杂一点的加权的计算方式，在完整代码中给出的是一个比较简单的求和方式，你也可以尝试在完整代码中将其修改成类似加权的形式。
