### ISSUE TITLE
数据下载

### ISSUE THREAD

**Issue by yearing1017** [datawhalechina/team-learning-rs#3]
请问天池的该比赛结束之后，还有别的途径下载数据吗

**Comment by RuyiLuo** [comment]
一般情况还是会以天池那边的下载渠道为主，如果需要的话我这边可以下载下来传到百度云上然后在新闻推荐项目的readme中给出另外一个下载链接

**Comment by hdd1009** [comment]
> 一般情况还是会以天池那边的下载渠道为主，如果需要的话我这边可以下载下来传到百度云上然后在新闻推荐项目的readme中给出另外一个下载链接

同学你好啊，这个比赛现在已经结束了，天池那边已经停止下载了。请问你本地有数据吗？能发给我一份吗？谢谢🙏

**Comment by RuyiLuo** [comment]
天池数据下载百度云连接：
链接：https://pan.baidu.com/s/15ReHXSM6VlQP-usia0DgYw 
提取码：135r

**Comment by GrangerZyj** [comment]
> 天池数据下载百度云连接： 链接：https://pan.baidu.com/s/15ReHXSM6VlQP-usia0DgYw 提取码：135r

大佬，请问推荐系统实战那个竞赛用户数据集在哪，我看路径上那些文件名字，好像和天池新闻赛那个不一样

trn_data_path = '/home/recsys/news_data/off_data/train_data.txt'
tst_data_path = '/home/recsys/news_data//off_data/test_data.txt'
user_info_data_path = '/home/recsys/news_data/off_data/user_info.txt'
doc_info_data_path = '/home/recsys/news_data/off_data/doc_info.txt

**Comment by cgscgs** [comment]
> 天池数据下载百度云连接： 链接：https://pan.baidu.com/s/15ReHXSM6VlQP-usia0DgYw 提取码：135r
大佬请问下，这里面的testA就是比赛中testB数据集吗？
