### ISSUE TITLE
基于新闻推荐 特征工程

### ISSUE THREAD

**Issue by jiangshu-cn** [datawhalechina/team-learning-rs#6]
特征工程中只有基于召回结果构建的监督数据集label都为0，没有找到构建label为1的日志数据的这部分代码，是省略了吗？

**Comment by RuyiLuo** [comment]
在给数据打标签的那一部分就是包括了label为0和为1的情况呀，为什么是只有label为0的呢？你那边的结果是发现label都是0么？那可能是召回部分效果不好导致的，所以打标签的时候没有1. 不知道我又没有理解到你的意思。

**Comment by jiangshu-cn** [comment]
大佬，非常感谢回答，我之前理解的是召回的物品结果集，都是用户没有访问过的物品，所以lable肯定为0，后来用基于物品的召回代码调试的时候也是没有发现lable为1的，您的意思是召回的结果中也有已经访问过的物品吗

**Comment by RuyiLuo** [comment]
召回的时候就把用户最后一次点击给去掉了，作为在做排序特征时候的真实点击标签，如果在去掉最后一次点击之后的召回过程中能召回到哪些真实的点击标签，这样的在排序特征里面label是1，相反就是0. 所以其实在召回的时候负样本(就是标签为0的)会特别多，一般就涉及到负采样了。特征工程的文档中应该都有

**Comment by jiangshu-cn** [comment]
大佬，谢谢解惑，我明白你的意思了
