### ISSUE TITLE
余弦相似度公式错误

### ISSUE THREAD

**Issue by aloneCR** [datawhalechina/team-learning-rs#7]
余弦相似度 余弦相似度衡量了两个向量的夹角，夹角越小越相似。首先从集合的角度描述余弦相似度，**相比于Jaccard公式来说就是分母有差异**，不是两个用户交互商品的并集的数量，而是两个用户分别交互的商品数量的乘积，公式如下：
$sim_{uv}=\frac{\|N(u)\| \cap \|N(v)\|}{\sqrt{\|N(u)\|\cdot\|N(v)\|}}$
这个公式有误，应该修改为：
$sim_{uv}=\frac{\|N(u) \cap N(v)\|}{\sqrt{\|N(u)\| \cdot\|N(v)\|}}$

**Comment by RuyiLuo** [comment]
是的，我这边已经修改好了，多谢提醒
