### ISSUE TITLE
md文件中公式显得错误

### ISSUE THREAD

**Issue by aloneCR** [datawhalechina/team-learning-rs#8]
![image](https://user-images.githubusercontent.com/30072589/112313109-76e2ba80-8ce2-11eb-92f4-090cf78a29d0.png)
公式还显示的源码

**Comment by RuyiLuo** [comment]
我这边用typora显示的话是没有问题的，你可以用typora试试（有时候typora刚打开也会有这个问题，关闭重新打开就可以了）

**Comment by aloneCR** [comment]
> 我这边用typora显示的话是没有问题的，你可以用typora试试（有时候typora刚打开也会有这个问题，关闭重新打开就可以了）

感谢，用typora打开确实就没有问题了。谢谢大佬
